spring:
  application:
    name: demo
  threads:
    virtual:
      enabled: true

services:
  customer-service:
    url: https://customers.destdomain.com/api/
  order-service:
    url: https://orders.destdomain.com/v1/
